# {{ ansible_managed }}

# ZSH completion to ignore case
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# ZSH opts
setopt NO_CASE_GLOB
setopt AUTO_CD

# GNUPG
GPG_TTY=$(tty)
export GPG_TTY

# Paths
export PATH=$PATH:/home/tharpem/.chefdk/gem/ruby/3.0.0/bin
export PATH=$PATH:/home/tharpem/go/bin

# System Commands
alias c='clear'
alias l='exa'
alias ls='exa'
alias ll='exa --header --long'
alias cat='bat'
alias grep='rg'
alias updatedb='sudo updatedb'
alias performance='sudo cpupower frequency-set -g performance'
alias powersave='sudo cpupower frequency-set -g powersave'

# Git Ops
alias git_all="printf "\\\\n" && find . -maxdepth 4 -type d -name \".git\" -execdir python -c 'import os; from termcolor import colored, cprint; cprint(colored(os.path.abspath(\".\"), \"blue\"))' \; -execdir git pull \;"

# MLocate Settings
alias updatedb='sudo updatedb'

# Editors
alias vi='nvim'
alias vim='nvim'

# Package Management
alias pinstall='sudo pacman -Syy --noconfirm '
alias premove='sudo pacman -R '
alias psearch='sudo pacman -Ss '
alias pupdate='sudo pacman -Syyu --noconfirm'
alias yinstall='yay -Syy --noconfirm '
alias yremove='yay -R '
alias ysearch='yay -Ss '
alias yupdate='yay -Syyu'

# Use Starship
eval "$(starship init zsh)"

# Setup Direnv
eval "$(direnv hook zsh)"
