---
- name: Install base packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - base-devel
    - linux-headers
    - yay

- name: Install common desktop packages
  yay:
    name: "{{ item }}" 
    update_cache: yes 
    state: present
  loop:
    - 1password
    - alacritty
    - auto-cpufreq
    - bat
    - consul
    - direnv
    - exa
    - google-chrome
    - htop
    - sysstat
    - mlocate
    - nautilus
    - nautilus-admin
    - nautilus-empty-file
    - neovim
    - nomad
    - noto-fonts
    - noto-fonts-compat
    - npm
    - owncloud-client
    - packer
    - powertop
    - preload
    - ripgrep
    - slack-desktop
    - speedtest-cli
    - terraform
    - tmux
    - transmission-gtk
    - vagrant
    - vault
    - virtualbox
    - visual-studio-code-bin
    - ansible
    - ansible-lint
    - chef-workstation
    - google-cloud-sdk
    - kubectl
    - gimp
    - blender
    - kubectl
    - starship
    - manjaro-printer
    - a52dec
    - faac
    - faad2
    - flac
    - jasper
    - lame
    - libdca
    - libdv
    - libmad
    - libmpeg2
    - libtheora
    - libvorbis
    - libxv
    - opus
    - wavpack
    - x264
    - xvidcore
    - python-pip
    - google-calendar-nativefier
    - dotnet-sdk
    - dotnet-runtime
    - nmap

- name: Remove common desktop packages
  pacman:
    name: "{{ item }}" 
    state: absent
  loop:
    - geary
    - firefox-gnome-theme-maia
    - firefox
    - sushi
    - evince
    - simple-scan
    - gnome-calendar
    - gnome-contacts
    - gnome-maps
    - gthumb
    - gnome-system-log
    - lollypop
    - gnome-todo
    - totem
    - caffeine-ng

- name: Restart vbox
  command: vboxreload
  
- name: Install PIP modules
  command: pip install termcolor

- name: Stat GCal Desktop Icon
  stat: 
    path: "/usr/share/applications/google-calendar-nativefier.desktop"
  register: gcal_stat

- name: Disable Google Calendar Built-in icon
  become: yes
  command: mv /usr/share/applications/google-calendar-nativefier.desktop /usr/share/applications/google-calendar-nativefier.desktop.not || true
  when: gcal_stat.stat.exists

- name: Stat Alacritty Desktop Icon
  stat: 
    path: "/usr/share/applications/Alacritty.desktop"
  register: alacritty_stat

- name: Disable Alacritty Built-in icon
  become: yes
  command: mv /usr/share/applications/Alacritty.desktop /usr/share/applications/Alacritty.desktop.not || true
  when: alacritty_stat.stat.exists

- name: Stat Gnome Terminal Desktop Icon
  stat: 
    path: "/usr/share/applications/org.gnome.Terminal.desktop"
  register: gnome_terminal_stat

- name: Disable Gnome-Terminal Built-in icon
  become: yes
  command: mv /usr/share/applications/org.gnome.Terminal.desktop /usr/share/applications/org.gnome.Terminal.desktop.not || true
  when: gnome_terminal_stat.stat.exists
