---
- name: Install base packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - base-devel
    - linux-headers
    - yay

- name: Install common desktop packages
  yay:
    name: "{{ item }}" 
    update_cache: yes 
    state: present
  loop:
    - 1password
    - alacritty
    - bat
    - consul
    - direnv
    - docker
    - docker-compose
    - exa
    - freeoffice
    - google-chrome
    - htop
    - sysstat
    - mlocate
    - nautilus
    - nautilus-admin
    - nautilus-empty-file
    - neovim
    - nomad
    - noto-fonts
    - npm
    - owncloud-client
    - packer
    - powertop
    - preload
    - ripgrep
    - slack-desktop
    - speedtest-cli
    - terraform
    - tmux
    - transmission-gtk
    - vagrant
    - vault
    - visual-studio-code-bin
    - ansible
    - ansible-lint
    - google-cloud-sdk
    - kubectl
    - gimp
    - blender
    - kubectl
    - starship
    - manjaro-printer
    - a52dec
    - faac
    - faad2
    - flac
    - font-manager
    - jasper
    - lame
    - libdca
    - libdv
    - libmad
    - libmpeg2
    - libtheora
    - libvorbis
    - libxv
    - opus
    - wavpack
    - x264
    - xvidcore
    - python-pip
    - python-psutil
    - dotnet-sdk
    - dotnet-runtime
    - nmap
    - manjaro-tools-iso
    - gdm-tools-git
    - preload
    - lm_sensors
    - xsensors
    - libdvdcss
    - ocs-url
    - gnome-clocks
    - gnome-weather

- name: Remove common desktop packages
  pacman:
    name: "{{ item }}" 
    state: absent
  loop:
    - geary
    - firefox-gnome-theme-maia
    - firefox
    - sushi
    - evince
    - simple-scan
    - gnome-calendar
    - gnome-contacts
    - gnome-maps
    - gthumb
    - gnome-system-log
    - lollypop
    - gnome-todo
    - totem
    - caffeine-ng

- name: Restart vbox
  command: vboxreload
  
- name: Install PIP modules
  command: pip install termcolor

- name: Start and Enable CUPS
  service:
    name: cups
    state: started
    enabled: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install npm packages
  command: npm install -g nativefier
