---
# Setup Alacritty and make it the default Terminal in Gnome
- name: Create a directory if it does not exist
  file:
    path: /home/{{ local_user }}/.config/alacritty
    state: directory
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0755'

- name: Template alacritty.yml
  copy:
    src: templates/alacritty.yml
    dest: /home/{{ local_user }}/.config/alacritty/alacritty.yml
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0644'

# Setup Starship prompt config
- name: Template starship.toml
  copy:
    src: templates/starship.toml
    dest: /home/{{ local_user }}/.config/starship.toml
    owner: "{{ local_user }}"
    group: wheel
    mode: '0644'

# Setup ZSHRC file
- name: Template .zshrc
  copy:
    src: templates/zshrc
    dest: /home/{{ local_user }}/.zshrc
    owner: "{{ local_user }}"
    group: wheel
    mode: '0600'
