---
# Setup Alacritty and make it the default Terminal in Gnome
- name: Create a directory if it does not exist
  file:
    path: /home/{{ local_user }}/.config/alacritty
    state: directory
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0755'

- name: Template alacritty.yml
  copy:
    src: templates/alacritty.yml
    dest: /home/{{ local_user }}/.config/alacritty/alacritty.yml
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0644'

- name: Template alacritty.desktop
  copy:
    src: templates/alacritty.desktop
    dest: /home/{{ local_user }}/.local/share/applications/alacritty.desktop
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0644'

- name: Stat GCal Desktop Icon
  stat: 
    path: "/usr/share/applications/google-calendar-nativefier.desktop"
  register: gcal_stat

- name: Disable Google Calendar Built-in icon
  become: yes
  command: mv /usr/share/applications/google-calendar-nativefier.desktop /usr/share/applications/google-calendar-nativefier.desktop.not
  when: gcal_stat.stat.exists

- name: Stat Alacritty Desktop Icon
  stat: 
    path: "/usr/share/applications/Alacritty.desktop"
  register: alacritty_stat

- name: Disable Alacritty Built-in icon
  become: yes
  command: mv /usr/share/applications/Alacritty.desktop /usr/share/applications/Alacritty.desktop.not
  when: alacritty_stat.stat.exists

- name: Stat Gnome Terminal Desktop Icon
  stat: 
    path: "/usr/share/applications/org.gnome.Terminal.desktop"
  register: gnome_terminal_stat

- name: Disable Gnome-Terminal Built-in icon
  become: yes
  command: mv /usr/share/applications/org.gnome.Terminal.desktop /usr/share/applications/org.gnome.Terminal.desktop.not
  when: gnome_terminal_stat.stat.exists


# Setup Starship prompt config
- name: Template starship.toml
  copy:
    src: templates/starship.toml
    dest: /home/{{ local_user }}/.config/starship.toml
    owner: "{{ local_user }}"
    group: wheel
    mode: '0644'

# Setup ZSHRC file
- name: Template .zshrc
  copy:
    src: templates/zshrc
    dest: /home/{{ local_user }}/.zshrc
    owner: "{{ local_user }}"
    group: wheel
    mode: '0600'

# Setup TMUX conf file
- name: Template .tmux.conf
  copy:
    src: templates/tmux.conf
    dest: /home/{{ local_user }}/.tmux.conf
    owner: "{{ local_user }}"
    group: wheel
    mode: '0600'

- name: Create tmux directory
  file:
    path: /home/{{ local_user }}/.tmux/plugins/tpm
    state: directory
    owner: "{{ local_user }}"
    group: "wheel"
    mode: '0755'

- name: Clone TPM repo
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{ local_user}}/.tmux/plugins/tpm

- name: Template .gitconfig
  copy:
    src: templates/gitconfig
    dest: /home/{{ local_user }}/.gitconfig
    owner: "{{ local_user }}"
    group: wheel
    mode: '0644'

# Setup Gmail Icon
- name: Template gmail.desktop
  copy:
    src: templates/gmail.desktop
    dest: /home/{{ local_user }}/.local/share/applications/gmail.desktop
    owner: "{{ local_user }}"
    group: wheel
    mode: '0644'

# Setup Gcal Icon
- name: Template gcal.desktop
  copy:
    src: templates/gcal.desktop
    dest: /home/{{ local_user }}/.local/share/applications/gcal.desktop
    owner: "{{ local_user }}"
    group: wheel
    mode: '0644'