---
- name: Check for Google Chrome binary
  ansible.builtin.stat:
    path: /usr/bin/google-chrome-stable
  register: google_chrome_bin
  tags: [third_party, chrome]

- name: Install Google Chrome from AUR
  ansible.builtin.command:
    cmd: "{{ common_aur_helper }} -S --noconfirm --needed google-chrome"
  become: true
  become_user: "{{ local_user }}"
  register: chrome_install
  changed_when: "'Nothing to do' not in chrome_install.stdout"
  when: not google_chrome_bin.stat.exists
  tags: [third_party, chrome]

- name: Ensure user applications directory exists
  ansible.builtin.file:
    path: /home/{{ local_user }}/.local/share/applications
    state: directory
    owner: "{{ local_user }}"
    group: wheel
    mode: "0755"
  become: true
  tags: [third_party, chrome]

- name: Deploy user google-chrome.desktop
  ansible.builtin.copy:
    src: templates/gnome_desktop/google-chrome.desktop
    dest: /home/{{ local_user }}/.local/share/applications/google-chrome.desktop
    owner: "{{ local_user }}"
    group: wheel
    mode: "0644"
  tags: [third_party, chrome]
