---
- name: Install Steam
  community.general.pacman:
    name: steam
    state: present
  become: true
  failed_when: false   # multilib repo must be enabled in /etc/pacman.conf
  tags: [third_party, steam]
