---
- name: Install Zoom from AUR
  ansible.builtin.command:
    cmd: "{{ common_aur_helper }} -S --noconfirm --needed zoom"
  become: true
  become_user: "{{ local_user }}"
  register: zoom_install
  changed_when: "'Nothing to do' not in zoom_install.stdout"
  tags: [third_party, zoom]
